sword-settings:
  sword-name: "&a&lPVP &aSword &7(Right-Click)"
  sword-material: DIAMOND_SWORD
  lore:
    - ""
    - "§7 A Simple Sword For PvP"
    - ""
  inventory-slot: "0"

armor-settings:
  helmet-name: "&a&lPVP &aHelmet"
  helmet-material: DIAMOND_HELMET
  chestplate-name: "&a&lPVP &aChestplate"
  chestplate-material: DIAMOND_CHESTPLATE
  leggings-name: "&a&lPVP &aLeggings"
  leggings-material: DIAMOND_LEGGINGS
  boots-name: "&a&lPVP &aBoots"
  boots-material: DIAMOND_BOOTS

kill-settings:
  kill-message: "&c&l☠ &c&l%killed_player% &cwas killed by &c&l%alive_player% &cin &cPVP Combat!"
  kill-streak-message: "&e&l⭐ &e%player% Now has a kill streak of &f&l%kill_streak%"
  lost-kill-streak-message: "&c&l✕ &c%player% kills have now been reset!"
  kill-commands:
    run-commands: false
    console-commands:
      - "give %player% minecraft:apple 1"

activation:
  time-to-activate: 2
  activation-countdown: "&a&lPVP &aActivating in &f%time% &aSecond(s)"
  activated: "&a&l✔ &a&lPVP &aActivated!"
  execute-console-commands: false
  console-commands:
    - "heal %player%"

deactivation:
  time-to-deactivate: 2
  deactivation-countdown: "&c&lPVP &cDeactivating in &f%time% &cSecond(s)"
  deactivated: "&c&l❌ &c&lPVP &cDeactivated!"
  execute-console-commands: false
  console-commands:
    - "fly %player%"

pvp-unactive:
  enable: false
  denied-hit-message: "&c&lPVP MANAGER &c%target% isn't in pvp mode!"
  not-in-pvp-message: "&c&lPVP MANAGER &cYou aren't in pvp mode %target%!"

pvp-active:
  sword-only: true
  denied-commands:
    - "/fly"
    - "/spawn"
    - "/home"
  deny-command-message: "&c&lPVP MANAGER &cSorry this command is blocked due to you being in PVP Combat!"

